name: Bug Report
description: Create a report to help us improve
labels: [bug]

body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
      
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
        
  - type: dropdown
    id: loottables-version
    attributes:
      label: LootTables Version
      description: What version of LootTables are you running?
      options:
        - v0.2.14 (Default)
        - v0.2.13 
        - v0.2.12 
        - v0.2.11
        - v0.2.10
        - v0.2.9
        - v0.2.8
        - v0.2.7
        - v0.2.6
        - v0.2.5
        - v0.2.3
        - v0.2.2
        - v0.2.1
        - v0.2.0
        - v0.1.6
        - v0.1.5
        - v0.1.4
        - v0.1.3
        - v0.1.2
        - v0.1.1
        - v0.1.0
    validations:
      required: true
      
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - v1.16.5 (Default)
    validations:
      required: true
        
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (generated JSONs, code snippets) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: markdown
    validations:
      required: true
