name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
           path: ~/.gradle/caches
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
           restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy build distribution
        run: cp build/distributions/*.zip loottables-distribution.zip

      - name: Attach build distribution from this build
        uses: actions/upload-artifact@v2
        with:
          name: LootTables distribution from this build
          path: ./loottables-distribution.zip

      # Publish to Sonatype OSS
      - name: Deploy
        run: .build/deploy.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
